services:
  server:
    build:
      context: .
    container_name: taskhub-server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TaskHub  # ← важно: db, не localhost
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 01032002ama
    networks:
      - taskhub-network
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: taskhub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: TaskHub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01032002ama
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - taskhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  taskhub-network: